language: java
sudo: false
install: true
jdk:
- oraclejdk8
dist: trusty
before_install:
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
before_deploy: "./gradlew prepareUpload"
deploy:
- provider: releases
  api_key:
    secure: SgLeQhFK8/2/8Eh+S7iSVxLiBudEYB1mDhn1UBfUlaBdmlnnDz/SOq7nv4W2LDtb6qmXZVDPcWikE3djA+/kqt+MnOAGQcec5YnIUn7AcZO8W4IME5yUOjmx61bpXyIJohhPc4SLqfErC1nxk8tgSWlB+LaBsq/kI+hPv6pxWDuMmV1a3FJ4MGG750DYUMhGJKVLZ7+V+GbkeI8GK9VNnywNKmrXwJnEhmA/ImYW0nK7uioUsNvGwJ29Ae2ewLBhb/b26ZOxkSaj06c92D7OO1e36qKE0qgv0KnfWa3e+wNaPAyN6xT4dU5t4JhjQuxhqisTdbdXj+xZUhTx9ZRg7spupcPMIarh+WeWfcTWH4FfWexLbZRk9hTtzyoy7W7ZqobFJVHZ568lv9FMnjNrT0qKPOxZXDtbjx3tdEpFRTXgUAgi/vFXtaOSLpUBVC2XLsmqnXOA4tj1nNUkBNNKMcwiEYZ12WBYwvk2dArDSrv0Ma7C/aKftX66YXLa1CSean+hPcpczSUpcaFnU8qqskVJEeWQyzNh0pPI/MurO3q/dD/tuf8xKOZi0u3XQB8XSnrReOPEYtkFH4ROq1sP1qZNQGoZQ/kABzT+GxqnCooWLYklZWrBvO9ITNV36myk+ry48D5I/NeFp/ijjCduJVH5pFWzdNptAY9+yvau6pM=
  file: 'build/libs/AnsiCastle.jar'
  on:
    repo: RanolP/AnsiCastle
    tags: true
- provider: bintray
  file: .bintraydescriptor.json
  user: ranolp
  key:
    secure: "L5O0sdvEnxWSDqUphz2Q4YMhShTJJ69cFga2yLlp3vcfZOYBzo3O05ElYUz/+yjTSfdI2S69R7/Uc2idKoLTa9+am0mjUHdWauowzNy7DvmsCZuXEkrxGuM5KXkCaX+uWMgNcSZf9idSWd2aw6Wz/zMbCD8Lm8eNSsk+MbIrLtUOKhEwAeFMZWWQmKCQJ2OMRbprDJ32231oS2y3DjjtjTOwrh3GH2qHVNFcepqsBAPjRoNQFT0jLuXy2eL+VwmcQkrwJ/o4PEg1NUMVY0sSrwi/eH1F7rRP+/vsHEbtCZ+stFg1u/M1KWkDl42pYspC1+6/+UaNTToIu2i2P8r79a4cYyJzGf31gtQM+B7DiZcNMBNkdTD6sz9wxxVnVtc2q5cgwgfxYJpJKZkoXKAXmNP5JpVumjOSaFmVWb8yzWI4IHp5Meu4UO/JE1Di1BGqwwo5f1CYAN0rFyqLAEV0cD6AYMi3vK+/ay1c7pGmM7mTpbRuCx84958tW/YGoRYojCqjMpIOexBGT58ymWZRYqHD9C2ZMZyHgCmJpf0Gs4hcnak8hbYYAsHo8b2XeXCAN+ZUOKJV6/QKfG7yhpC+y3g4y5QRvDBNwnczMBrJcROGl/oesN96c/2fMUP/kgq/qx2RxWsffhL68HF5gFCgRLh6HRzOeBvjr9HrTI6lDzA="
  skip_cleanup: true
  on:
    repo: RanolP/AnsiCastle
    tags: true
